# Generated by Django 3.2.4 on 2023-06-14 16:25

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon', '0002_alter_coupon_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ انقضا'),
        ),
    ]
