# Generated by Django 3.2.4 on 2023-06-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_suggest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='اسلاگ (نامک)'),
        ),
    ]
