# Generated by Django 3.2.4 on 2023-06-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20230613_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='commentCount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likeCount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='viewCount',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قمیت'),
        ),
    ]
