# Generated by Django 3.2.4 on 2023-06-06 18:28

import Category.models
from django.db import migrations, models
import django_jalali.db.models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Category.models.upload_image, validators=[utils.validator.validate_file_size], verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
