# Generated by Django 3.2.4 on 2023-06-07 11:24

import Article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0005_alter_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.CharField(blank=True, max_length=50, unique=True, verbose_name='اسلاگ (نامک)')),
                ('body', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(null=True, upload_to=Article.models.upload_image, verbose_name='عکس')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('publish', 'انتشار'), ('done', 'پایان انتشار')], default='draft', max_length=50, verbose_name='وضعیت')),
                ('viewCount', models.IntegerField(default=0, verbose_name='تعداد بازدید ها')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='Category.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
