# Generated by Django 3.2.4 on 2023-06-07 10:28

import User.managers
import User.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست.', regex='(^\\+?(09|98|0)?(9([0-9]{9}))$)')], verbose_name='شماره موبایل')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='آخرین ورود')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='آیا مدیر است؟')),
                ('is_active', models.BooleanField(default=False, verbose_name='آیا فعال است؟')),
                ('is_staff', models.BooleanField(default=False, verbose_name='آیا کارمند است؟')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=User.models.upload_avatar, verbose_name='عکس پروفایل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', User.managers.UserManager()),
            ],
        ),
    ]
