# Generated by Django 3.2.4 on 2023-06-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_alter_category_parent'),
        ('Product', '0010_suggest'),
        ('Call_Price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callprice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='Category.category', verbose_name='نوع دسته بندی'),
        ),
        migrations.AlterField(
            model_name='callprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Product.product', verbose_name='نام محصول'),
        ),
    ]
