# Generated by Django 3.2.4 on 2023-06-07 11:08

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Call_Price', '0002_auto_20230606_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callprice',
            old_name='compony_name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='callprice',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='callprice',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
