# Generated by Django 3.2.4 on 2023-06-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Call_Price', '0003_auto_20230607_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
