# Generated by Django 3.2.4 on 2023-06-12 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('family', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='موبایل')),
                ('address1', models.TextField(verbose_name='آدرس 1')),
                ('address2', models.TextField(blank=True, null=True, verbose_name='آدرس 2')),
                ('post_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')], verbose_name='کد پستی')),
                ('payment_type', models.CharField(blank=True, choices=[('online', 'آنلاین'), ('cash', 'نقدی')], max_length=6, null=True, verbose_name='نوع پرداخت')),
                ('status', models.CharField(blank=True, choices=[('sending', 'درحال ارسال'), ('posted', 'ارسال شده'), ('delivered', 'تحویل داده شده')], default='sending', max_length=9, null=True, verbose_name='وضعیت ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.color', verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
